### ISSUE TITLE
Incorrect shape and color of interactive points when shapes with lines are used

### ISSUE THREAD

**Issue by nicokist** [davidgohel/ggiraph#252] opened 2023-01-20 11:21 UTC
Hello,

Thanks for this amazing package, I've really been able to have a lot of fun with it!

I recently come across some surprising behavior: when `tooltip` is added to the aesthetics some of the points seem to no longer be colored correctly. Please find a reprex attached:

This problem goes away once the `tooltip` is removed from the aesthetics.

``` r
library(tidyverse)
library(ggiraph)

dat <- structure(list(x = c(
  0.670700732152909, 0.94666058011353, 0.271530218888074,
  0.28272072202526, 0.950930949067697, 0.774316143942997, 0.951495578512549,
  0.277329422067851, 0.424100575968623, 0.454079832881689
), y = c(
  0.29804180865176,
  0.434860641835257, 0.568946241633967, 0.701763016404584, 0.12649045791477,
  0.37094813096337, 0.728182743070647, 0.256948527181521, 0.562205084599555,
  0.570892055518925
), genus = c(
  2L, 1L, 2L, 1L, 1L, 1L, 2L, 1L,
  2L, 2L
), genus_species = c(
  "2_1", "1_2", "2_2", "1_1", "1_1",
  "1_1", "2_1", "1_2", "2_2", "2_2"
)), row.names = c(NA, -10L), class = c(
  "tbl_df",
  "tbl", "data.frame"
))

dat |>
  mutate(
    genus = factor(genus),
    genus_species = factor(genus_species)
  ) |>
  ggplot() +
    aes(x = x, y = y, col = `genus`, shape = genus_species, tooltip = genus_species) +
    geom_point()
```

![](https://i.imgur.com/cp1LdYx.png)

Left bottom point (~0.25, ~0.25) correct color and shape

``` r



dat |>
    mutate(
        genus = factor(genus),
        genus_species = factor(genus_species)
    ) |>
    ggplot() +
    aes(x = x, y = y, col = `genus`, shape = genus_species, tooltip = genus_species) +
    geom_point_interactive()
```

![](https://i.imgur.com/eYZ1LkL.png)
Left bottom point (~0.25, ~0.25) incorrect color
``` r

sessionInfo()
#> R version 4.2.2 (2022-10-31)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Ventura 13.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] ggiraph_0.8.5   forcats_0.5.2   stringr_1.4.1   dplyr_1.0.10   
#>  [5] purrr_0.3.5     readr_2.1.3     tidyr_1.2.1     tibble_3.1.8   
#>  [9] ggplot2_3.4.0   tidyverse_1.3.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9          lubridate_1.9.0     assertthat_0.2.1   
#>  [4] digest_0.6.30       utf8_1.2.2          R6_2.5.1           
#>  [7] cellranger_1.1.0    backports_1.4.1     reprex_2.0.2       
#> [10] evaluate_0.18       httr_1.4.4          highr_0.9          
#> [13] pillar_1.8.1        rlang_1.0.6         uuid_1.1-0         
#> [16] googlesheets4_1.0.1 readxl_1.4.1        rstudioapi_0.14    
#> [19] R.utils_2.12.2      R.oo_1.25.0         rmarkdown_2.18     
#> [22] styler_1.8.1        labeling_0.4.2      googledrive_2.0.0  
#> [25] htmlwidgets_1.5.4   munsell_0.5.0       broom_1.0.1        
#> [28] compiler_4.2.2      modelr_0.1.10       xfun_0.35          
#> [31] systemfonts_1.0.4   pkgconfig_2.0.3     htmltools_0.5.3    
#> [34] tidyselect_1.2.0    fansi_1.0.3         crayon_1.5.2       
#> [37] tzdb_0.3.0          dbplyr_2.2.1        withr_2.5.0        
#> [40] R.methodsS3_1.8.2   grid_4.2.2          jsonlite_1.8.3     
#> [43] gtable_0.3.1        lifecycle_1.0.3     DBI_1.1.3          
#> [46] magrittr_2.0.3      scales_1.2.1        cli_3.4.1          
#> [49] stringi_1.7.8       farver_2.1.1        fs_1.5.2           
#> [52] xml2_1.3.3          ellipsis_0.3.2      generics_0.1.3     
#> [55] vctrs_0.5.1         tools_4.2.2         R.cache_0.16.0     
#> [58] glue_1.6.2          hms_1.1.2           fastmap_1.1.0      
#> [61] yaml_2.3.6          timechange_0.1.1    colorspace_2.0-3   
#> [64] gargle_1.2.1        rvest_1.0.3         knitr_1.41         
#> [67] haven_2.5.1
```

<sup>Created on 2023-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidgohel** [comment] 2023-01-20 17:58
thank you for reporting this, we will try to fix soon!

**Comment by sigmapi** [comment] 2023-08-30 13:35
Thanks @nicokist . The bug occurs when some points have shapes with lines (like a cross or an X). Created a fix and it will be included in the next version.

**Comment by sigmapi** [comment] 2023-08-30 13:40
Thanks @sda030 . What you describe is unrelated with the original issue.
The problem is that in that case you should explicitly specify a `group` aesthetic:

`mapping = ggplot2::aes(tooltip = .data_label, group = .category)`

Adding an interactive aesthetic like `tooltip`,  sometimes alters the original grouping that ggplot2 does implicitly, even if you don't specify the group aesthetic. In those cases you must specify the group aesthetic in order to get the graph correctly rendered.

**Closed** 2023-08-30 14:35 UTC
Labels: bug
