### ISSUE TITLE
object 'GeomInteractivePath' not found

### ISSUE THREAD

**Issue by sdlugosz** [davidgohel/ggiraph#80] opened 2017-11-09 08:17 UTC
This error occurs when using `geom_segment_interactive` (version 0.4.0 from cran).
Maybe `GeomPathInteractive` should be referenced? The following line solves the problem for me:
`GeomInteractivePath <- ggiraph:::GeomPathInteractive`

**Comment by davidgohel** [comment] 2017-11-09 09:15
I can't reproduce, I am using the `0.4.1` version from CRAN.

Can you add a reproducible example and `sessionInfo()`?

**Comment by sdlugosz** [comment] 2017-11-09 10:34
The error occurs if `coord_map()` is used in ggplot.

```
library(ggiraph)
sessionInfo()
tmp <- data.frame(x = c(1,2),
                  y = c(3,4),
                  xend = c(5,6),
                  yend = c(7,8),
                  tooltip = c("A", "B"))
ggplot() +
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend), data = tmp) +
  coord_map()
test1 <- ggplot() +
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend), data = tmp)
ggiraph(code = print(test1))
test2 <- ggplot() +
  geom_segment_interactive(aes(x = x, y = y, xend = xend, yend = yend, tooltip=tooltip), data = tmp) +
  coord_map()
ggiraph(code = print(test2))
```

The first two plots work. The third gives results in an error.


session_info:

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggiraph_0.4.0        ggplot2_2.2.1        RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      xml2_1.1.1        bindr_0.1         magrittr_1.5      uuid_0.1-2        munsell_0.4.3     colorspace_1.3-2 
 [8] R6_2.2.2          rlang_0.1.2.9000  plyr_1.8.4        dplyr_0.7.2       tools_3.4.1       grid_3.4.1        gtable_0.2.0     
[15] rvg_0.1.4         R.oo_1.21.0       htmltools_0.3.6   assertthat_0.2.0  yaml_2.1.14       lazyeval_0.2.0    digest_0.6.12    
[22] tibble_1.3.4      zip_1.0.0         bindrcpp_0.2      purrr_0.2.3       officer_0.1.6     base64enc_0.1-3   htmlwidgets_0.9  
[29] R.utils_2.5.0     glue_1.1.1        compiler_3.4.1    RevoUtils_10.0.5  gdtools_0.1.5     scales_0.5.0      R.methodsS3_1.7.1
[36] pkgconfig_2.0.1

**Comment by davidgohel** [comment] 2017-11-09 10:42
Thanks, I can reproduce... 

OK, I will fix that for next week

**Comment by davidgohel** [comment] 2017-12-18 13:08
thanks, fixed in the dev version

**Closed by davidgohel** 2017-12-18 13:08 UTC
