### ISSUE TITLE
ggiraph package won't install on Ubuntu 24.04

### ISSUE THREAD

**Issue by amongoodtx** [davidgohel/ggiraph#311] opened 2024-11-22 23:57 UTC
I was able to successfully install ggiraph on a system running Ubuntu 20.04 (R version 4.3.3)  but not Ubuntu 24.04 (R version 4.4.2). I get the following error: 
```
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/print.h: In function ‘void Rcpp::warningcall(SEXP, const std::string&)’:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/print.h:30:19: error: format not a string literal and no format arguments [-Werror=format-security]
   30 |     Rf_warningcall(call, s.c_str());
```

**Comment by davidgohel** [comment] 2024-11-23 09:10
duplicate of https://stackoverflow.com/questions/79216916/problem-installing-ggiraph-on-ubuntu-24-04

**Closed by davidgohel** 2024-11-23 09:10 UTC
