### ISSUE TITLE
Unable to install ggiraph  

### ISSUE THREAD

**Issue by TrueCactus** [davidgohel/ggiraph#225] opened 2022-06-17 14:59 UTC
Hello ,

I am trying to install ggiraph on my server. But it's not working. Do you have any idea how to successfully install it ? 
(I try to install it via R STUDIO , it's not working too).

Thanks for your help.

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

- **Logs** 
```
Installing package into ‘/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/ggiraph_0.8.2.tar.gz'
Content type 'application/x-gzip' length 358242 bytes (349 KB)
==================================================
downloaded 349 KB

* installing *source* package ‘ggiraph’ ...
** package ‘ggiraph’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c a_color.cpp -o a_color.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c clip.cpp -o clip.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c dsvg.cpp -o dsvg.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c dsvg_dev.cpp -o dsvg_dev.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c geom.cpp -o geom.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c indexed.cpp -o indexed.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c interactive.cpp -o interactive.o
interactive.cpp: In function ‘std::string compile_css(const string&, const char*, const string&, const char*, const char*, const char*)’:
interactive.cpp:85:46: error: no matching function for call to ‘regex_replace(const char*&, std::regex&, std::string&)’
   return std::regex_replace(css, pattern, cls);
                                              ^
interactive.cpp:85:46: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from interactive.cpp:5:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
interactive.cpp:85:46: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘std::basic_string<char>’)
   return std::regex_replace(css, pattern, cls);
                                              ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from interactive.cpp:5:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
interactive.cpp:85:46: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char*’
   return std::regex_replace(css, pattern, cls);
                                              ^
make: *** [interactive.o] Error 1
ERROR: compilation failed for package ‘ggiraph’
* removing ‘/home/webmaster/R/x86_64-pc-linux-gnu-library/4.2/ggiraph’

The downloaded source packages are in
	‘/tmp/RtmpUwoAB9/downloaded_packages’
Warning message:
In install.packages("ggiraph", repos = "http://cran.rstudio.com/") :
  installation of package ‘ggiraph’ had non-zero exit status
```

-  **the command I run :**
`install.packages("ggiraph", repos = "http://cran.rstudio.com/")`

-  **My  `sessionInfo()` results :**
```

R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0
```

**Comment by davidgohel** [comment] 2022-06-17 18:29
#hhhhdqhHwg

**Comment by cwbcm** [comment] 2022-07-01 16:06
Hi, I ran into this same error.

**Comment by davidgohel** [comment] 2022-07-01 16:15
Sorry, the previous message was unintended, probably my son!

**Comment by davidgohel** [comment] 2022-07-01 16:32
That's not something we can fix. The message says:

> error: no matching function for call to ‘regex_replace(`

and you are using GCC < 4.9 that doesn't support regex. 

My google-fu (I looked for the error message you had) brought me to that page: https://stackoverflow.com/a/65179052/3315962

It explains better that I could do what you could do :)

**Comment by cwbcm** [comment] 2022-07-01 17:04
Thanks for the reply! I will try updating the GCC version.

**Comment by davidgohel** [comment] 2022-07-04 07:59
Closing the issue. 

We can not easily spend time installing centos7 to reproduce an issue with compilation. 

If you want us to check, please provide a reproducible example, in that case, it probably means a docker image with your set up.

**Closed by davidgohel** 2022-07-04 07:59 UTC
