### ISSUE TITLE
geom_text_interactive() opacity toggle with girafe_css() not working

### ISSUE THREAD

**Issue by derekouyang** [davidgohel/ggiraph#308] opened 2024-11-13 04:05 UTC
For the example in https://www.ardata.fr/ggiraph-book/examples.html, as of at least 0.8.4, the text that is supposed to show up on hover on the top left of the plot no longer shows up. As far as I can tell, properties of geom_text_interactive() are no longer able to be adjusted using girafe_css().

```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22631)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
 [1] extrafont_0.19  cowplot_1.1.3  
 [3] glue_1.6.2      ggiraph_0.8.10 
 [5] ggtext_0.1.2    ggthemes_5.1.0 
 [7] forcats_0.5.2   stringr_1.5.0  
 [9] dplyr_1.1.4     purrr_1.0.0    
[11] readr_2.1.3     tidyr_1.2.1    
[13] tibble_3.2.1    ggplot2_3.5.1  
[15] tidyverse_1.3.2

loaded via a namespace (and not attached):
 [1] tidytuesdayR_1.1.2 
 [2] httr_1.4.4         
 [3] jsonlite_1.8.4     
 [4] modelr_0.1.10      
 [5] assertthat_0.2.1   
 [6] googlesheets4_1.0.1
 [7] cellranger_1.1.0   
 [8] yaml_2.3.6         
 [9] Rttf2pt1_1.3.12    
[10] pillar_1.9.0       
[11] backports_1.4.1    
[12] extrafontdb_1.0    
[13] uuid_1.1-0         
[14] digest_0.6.31      
[15] gridtext_0.1.5     
[16] rvest_1.0.3        
[17] colorspace_2.0-3   
[18] htmltools_0.5.4    
[19] pkgconfig_2.0.3    
[20] broom_1.0.2        
[21] haven_2.5.1        
[22] scales_1.3.0       
[23] tzdb_0.3.0         
[24] timechange_0.1.1   
[25] proxy_0.4-27       
[26] googledrive_2.0.0  
[27] generics_0.1.3     
[28] ellipsis_0.3.2     
[29] withr_2.5.0        
[30] cli_3.5.0          
[31] magrittr_2.0.3     
[32] crayon_1.5.2       
[33] readxl_1.4.1       
[34] evaluate_0.19      
[35] fs_1.5.2           
[36] fansi_1.0.3        
[37] xml2_1.3.3         
[38] class_7.3-20       
[39] tools_4.2.2        
[40] hms_1.1.2          
[41] gargle_1.2.1       
[42] lifecycle_1.0.3    
[43] munsell_0.5.0      
[44] reprex_2.0.2       
[45] compiler_4.2.2     
[46] e1071_1.7-12       
[47] systemfonts_1.1.0  
[48] rlang_1.1.4        
[49] classInt_0.4-8     
[50] units_0.8-1        
[51] grid_4.2.2         
[52] rstudioapi_0.14    
[53] htmlwidgets_1.6.2  
[54] rmarkdown_2.19     
[55] gtable_0.3.1       
[56] DBI_1.1.3          
[57] R6_2.5.1           
[58] lubridate_1.9.0    
[59] knitr_1.41         
[60] fastmap_1.1.1      
[61] utf8_1.2.2         
[62] KernSmooth_2.23-20 
[63] stringi_1.7.8      
[64] Rcpp_1.0.13        
[65] vctrs_0.6.5        
[66] sf_1.0-16          
[67] dbplyr_2.2.1       
[68] tidyselect_1.2.0   
[69] xfun_0.36 
```

**Comment by davidgohel** [comment] 2024-11-19 09:16
As far as I can tell, properties of geom_text_interactive() are still working as expected. 

I am closing the issue as I can't reproduce it. If you have a reprex that shows the issue, please share it and I'll reopen the issue :)


````
departures <- tibble::tibble(
  coname = c(
    "BARRICK GOLD ", "BARRICK GOLD ", "BARRICK GOLD ", "DANA", "DANA",
    "DUN & BRADSTREET ", "DUN & BRADSTREET ", "DUN & BRADSTREET ",
    "SEARS HOLDINGS ", "TOYS R US", "TOYS R US", "TOYS R US", "TOYS R US",
    "FEDERAL HOME LOAN MORTG ", "CARPENTER TECHNOLOGY ", "CLAIRES STORES",
    "FEDERAL-MOGUL HOLDINGS ", "ENESCO GROUP", "ENESCO GROUP", "WAUSAU PAPER ",
    "WAUSAU PAPER ", "WAUSAU PAPER ", "WAUSAU PAPER ", "WAUSAU PAPER ",
    "CALLAWAY GOLF CO", "CALLAWAY GOLF CO", "CALLAWAY GOLF CO", "NTN BUZZTIME",
    "ION GEOPHYSICAL ", "CHECKERS DRIVE-IN RESTAURANT",
    "CHECKERS DRIVE-IN RESTAURANT", "SEARS HOLDINGS ", "CDI ",
    "CHECKERS DRIVE-IN RESTAURANT", "BARNES & NOBLE", "BARNES & NOBLE",
    "ION GEOPHYSICAL ", "CARPENTER TECHNOLOGY ", "BARRICK GOLD ",
    "FEDERAL-MOGUL HOLDINGS ", "CHECKERS DRIVE-IN RESTAURANT",
    "FEDERAL HOME LOAN MORTG ", "BARNES & NOBLE", "NTN BUZZTIME",
    "CARPENTER TECHNOLOGY ", "ENESCO GROUP", "CDI ", "ION GEOPHYSICAL ",
    "CHECKERS DRIVE-IN RESTAURANT", "WAUSAU PAPER ", "CLAIRES STORES",
    "CLAIRES STORES", "BARRICK GOLD ", "ION GEOPHYSICAL ", "NTN BUZZTIME",
    "GREAT ELM CAPITAL GROUP", "TOYS R US", "ION GEOPHYSICAL ",
    "CHECKERS DRIVE-IN RESTAURANT", "GREAT ELM CAPITAL GROUP",
    "DUN & BRADSTREET ", "SEARS HOLDINGS ", "CALLAWAY GOLF CO", "CDI ",
    "ENESCO GROUP", "CHRISTOPHER & BANKS ", "CHRISTOPHER & BANKS ",
    "CHECKERS DRIVE-IN RESTAURANT", "GREAT ELM CAPITAL GROUP",
    "DUN & BRADSTREET ", "ENESCO GROUP", "CDI ", "BARRICK GOLD ",
    "FEDERAL-MOGUL HOLDINGS ", "FEDERAL-MOGUL HOLDINGS ", "DUN & BRADSTREET ",
    "SEARS HOLDINGS ", "FEDERAL HOME LOAN MORTG ", "ENESCO GROUP",
    "ION GEOPHYSICAL ", "DANA", "ENESCO GROUP", "CALLAWAY GOLF CO",
    "SEARS HOLDINGS ", "SEARS HOLDINGS ", "CALLAWAY GOLF CO",
    "FEDERAL-MOGUL HOLDINGS ", "TOYS R US", "NTN BUZZTIME", "ION GEOPHYSICAL ",
    "GREAT ELM CAPITAL GROUP", "TOYS R US", "CARPENTER TECHNOLOGY ",
    "CHRISTOPHER & BANKS ", "BIOLASE", "BIOLASE", "BIOLASE", "BIOLASE", "BIOLASE",
    "DANA", "DANA", "NTN BUZZTIME", "GREAT ELM CAPITAL GROUP",
    "FEDERAL HOME LOAN MORTG ", "BARRICK GOLD ", "BARRICK GOLD ",
    "CLAIRES STORES", "CLAIRES STORES", "DANA", "WAUSAU PAPER ",
    "FEDERAL HOME LOAN MORTG ", "FEDERAL HOME LOAN MORTG ", "NTN BUZZTIME",
    "BARNES & NOBLE", "CARPENTER TECHNOLOGY ", "CARPENTER TECHNOLOGY ",
    "NTN BUZZTIME", "CARPENTER TECHNOLOGY ", "CHRISTOPHER & BANKS ", "CDI ",
    "CDI ", "DANA", "SEARS HOLDINGS ", "CALLAWAY GOLF CO", "CHRISTOPHER & BANKS ",
    "CHRISTOPHER & BANKS ", "BARNES & NOBLE", "CLAIRES STORES",
    "FEDERAL HOME LOAN MORTG ", "FEDERAL-MOGUL HOLDINGS ", "SEARS HOLDINGS ",
    "CLAIRES STORES", "NTN BUZZTIME", "CHRISTOPHER & BANKS ",
    "GREAT ELM CAPITAL GROUP", "DUN & BRADSTREET ", "FEDERAL-MOGUL HOLDINGS ",
    "CDI ", "WAUSAU PAPER ", "BIOLASE", "FEDERAL-MOGUL HOLDINGS ",
    "GREAT ELM CAPITAL GROUP", "TOYS R US", "BIOLASE", "BARNES & NOBLE",
    "GREAT ELM CAPITAL GROUP", "CLAIRES STORES", "BARNES & NOBLE"
  ),
  main_cause = factor(
    rep(
      rep(c("voluntary", "involuntary"), 30),
      c(
        7L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 9L, 3L, 1L, 1L, 2L, 1L, 4L, 2L, 1L, 1L, 1L,
        1L, 5L, 1L, 11L, 3L, 8L, 1L, 4L, 1L, 2L, 1L, 2L, 3L, 4L, 4L, 1L, 1L, 1L, 2L,
        1L, 1L, 4L, 2L, 2L, 1L, 8L, 1L, 1L, 1L, 5L, 2L, 2L, 2L, 1L, 5L, 1L, 1L, 3L,
        2L, 1L, 2L
      )
    ),
    levels = c("voluntary", "involuntary")
  ),
  tooltip = c(
    "Firm: BARRICK GOLD \nCEO: Peter Munk C.C.\nYear: 1997\nMotive: Voluntary turnover",
    "Firm: BARRICK GOLD \nCEO: Peter Munk C.C.\nYear: 2008\nMotive: Departure following a marger adquisition",
    "Firm: BARRICK GOLD \nCEO: Gregory C. Wilkins\nYear: 2007\nMotive: Health Concerns",
    "Firm: DANA\nCEO: Southwood J. Morcott\nYear: 1998\nMotive: Voluntary turnover",
    "Firm: DANA\nCEO: Joseph M. Magliochetti\nYear: 2003\nMotive: Death",
    "Firm: DUN & BRADSTREET \nCEO: Charles W. Moritz\nYear: 1993\nMotive: Voluntary turnover",
    "Firm: DUN & BRADSTREET \nCEO: Robert E. Weissman\nYear: 1996\nMotive: Departure following a marger adquisition",
    "Firm: DUN & BRADSTREET \nCEO: Volney Taylor\nYear: 1999\nMotive: Job performance",
    "Firm: SEARS HOLDINGS \nCEO: Joseph E. Antonini\nYear: 1994\nMotive: Job performance",
    "Firm: TOYS R US\nCEO: Charles P. Lazarus\nYear: 1993\nMotive: Voluntary turnover",
    "Firm: TOYS R US\nCEO: Robert C. Nakasone\nYear: 1999\nMotive: Job performance",
    "Firm: TOYS R US\nCEO: Michael Goldstein\nYear: 1997\nMotive: Voluntary turnover",
    "Firm: TOYS R US\nCEO: Richard L. Markee\nYear: 2005\nMotive: Job performance",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: Leland C. Brendsel\nYear: 2002\nMotive: Job performance",
    "Firm: CARPENTER TECHNOLOGY \nCEO: Robert W. Cardy\nYear: 2001\nMotive: Voluntary turnover",
    "Firm: CLAIRES STORES\nCEO: Rowland Schaefer\nYear: 2002\nMotive: Health Concerns",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Dennis J. Gormley\nYear: 1996\nMotive: Job performance",
    "Firm: ENESCO GROUP\nCEO: G. William Seawright\nYear: 1997\nMotive: Voluntary turnover",
    "Firm: ENESCO GROUP\nCEO: Alejandro Diaz\nYear: 1993\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: Arnold M. Nemirow\nYear: 1994\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: Daniel D. King\nYear: 1997\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: Thomas J. Howatt\nYear: 2011\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: San W. Orr Jr.\nYear: 1995\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: San W. Orr, Jr.\nYear: 2000\nMotive: Voluntary turnover",
    "Firm: CALLAWAY GOLF CO\nCEO: Ely R. Callaway\nYear: 1995\nMotive: Voluntary turnover",
    "Firm: CALLAWAY GOLF CO\nCEO: Ely R. Callaway\nYear: 2000\nMotive: Health Concerns",
    "Firm: CALLAWAY GOLF CO\nCEO: Donald H. Dye\nYear: 1998\nMotive: Job performance",
    "Firm: NTN BUZZTIME\nCEO: Patrick J. Downs\nYear: 1996\nMotive: Job performance",
    "Firm: ION GEOPHYSICAL \nCEO: Gary D. Owens\nYear: 1996\nMotive: Job performance",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: James E. Mattei\nYear: 1993\nMotive: Voluntary turnover",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: James F. White, Jr.\nYear: 1995\nMotive: Policy related problems",
    "Firm: SEARS HOLDINGS \nCEO: Floyd Hall\nYear: 1999\nMotive: Voluntary turnover",
    "Firm: CDI \nCEO: Walter R. Garrison\nYear: 1996\nMotive: Voluntary turnover",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: Albert J. DiMarco\nYear: 1996\nMotive: Job performance",
    "Firm: BARNES & NOBLE\nCEO: Leonard Riggio\nYear: 2001\nMotive: Voluntary turnover",
    "Firm: BARNES & NOBLE\nCEO: Leonard Riggio\nYear: 2016\nMotive: Voluntary turnover",
    "Firm: ION GEOPHYSICAL \nCEO: Charles E. Selecman\nYear: 1997\nMotive: Voluntary turnover",
    "Firm: CARPENTER TECHNOLOGY \nCEO: Robert J. Torcolini\nYear: 2006\nMotive: Voluntary turnover",
    "Firm: BARRICK GOLD \nCEO: Randall Oliphant\nYear: 2002\nMotive: Job performance",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Richard A. Snell\nYear: 2000\nMotive: Job performance",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: C. Thomas Thompson\nYear: 1997\nMotive: Voluntary turnover",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: Gregory J. Parseghian\nYear: 2003\nMotive: Job performance",
    "Firm: BARNES & NOBLE\nCEO: Stephen Riggio\nYear: 2009\nMotive: Voluntary turnover",
    "Firm: NTN BUZZTIME\nCEO: Gerald Sokol Jr.\nYear: 1998\nMotive: Job performance",
    "Firm: CARPENTER TECHNOLOGY \nCEO: Dennis M. Draeger\nYear: 2003\nMotive: Voluntary turnover",
    "Firm: ENESCO GROUP\nCEO: Jeffrey A. Hutsell\nYear: 1999\nMotive: Voluntary turnover",
    "Firm: CDI \nCEO: Mitch Wienick\nYear: 2000\nMotive: Voluntary turnover",
    "Firm: ION GEOPHYSICAL \nCEO: W. J. Zerinque\nYear: 1998\nMotive: Voluntary turnover",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: James J. Gillespie\nYear: 1999\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: Daniel R. Olvey\nYear: 1999\nMotive: Job performance",
    "Firm: CLAIRES STORES\nCEO: Marla L. Schaefer\nYear: 2003\nMotive: Departure following a marger adquisition",
    "Firm: CLAIRES STORES\nCEO: E. Bonnie Schaefer\nYear: 2006\nMotive: Departure following a marger adquisition",
    "Firm: BARRICK GOLD \nCEO: Paul D. Melnuk\nYear: 1998\nMotive: When to work in other company",
    "Firm: ION GEOPHYSICAL \nCEO: Sam K. Smith\nYear: 1999\nMotive: Voluntary turnover",
    "Firm: NTN BUZZTIME\nCEO: Stanley B. Kinsey\nYear: 2006\nMotive: Voluntary turnover",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Alain Rossmann\nYear: 2000\nMotive: Voluntary turnover",
    "Firm: TOYS R US\nCEO: John H. Eyler Jr.\nYear: 2004\nMotive: Voluntary turnover",
    "Firm: ION GEOPHYSICAL \nCEO: Timothy J. Probert\nYear: 2002\nMotive: Voluntary turnover",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: Daniel J. Dorsch\nYear: 2002\nMotive: Voluntary turnover",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Michael C. Mulica\nYear: 2013\nMotive: Voluntary turnover",
    "Firm: DUN & BRADSTREET \nCEO: Allan Z. Loren\nYear: 2004\nMotive: Voluntary turnover",
    "Firm: SEARS HOLDINGS \nCEO: Charles C. Conaway\nYear: 2001\nMotive: Policy related problems",
    "Firm: CALLAWAY GOLF CO\nCEO: Ronald A. Drapeau\nYear: 2004\nMotive: Job performance",
    "Firm: CDI \nCEO: Allen M. Levantin\nYear: 2001\nMotive: Job performance",
    "Firm: ENESCO GROUP\nCEO: John F. Cauley\nYear: 2000\nMotive: Departure following a marger adquisition",
    "Firm: CHRISTOPHER & BANKS \nCEO: William J. Prange\nYear: 2005\nMotive: Health Concerns",
    "Firm: CHRISTOPHER & BANKS \nCEO: Joseph E. Pennington\nYear: 2006\nMotive: Voluntary turnover",
    "Firm: CHECKERS DRIVE-IN RESTAURANT\nCEO: Keith Sirois\nYear: 2005\nMotive: Departure following a marger adquisition",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Donald J. Listwin\nYear: 2004\nMotive: Voluntary turnover",
    "Firm: DUN & BRADSTREET \nCEO: Steven W. Alesio\nYear: 2009\nMotive: Voluntary turnover",
    "Firm: ENESCO GROUP\nCEO: Daniel DalleMolle\nYear: 2003\nMotive: Death",
    "Firm: CDI \nCEO: Roger H. Ballou\nYear: 2010\nMotive: Voluntary turnover",
    "Firm: BARRICK GOLD \nCEO: Jamie Calvin Sokalsky C.A. C.P.A. CA Honours B\nYear: 2014\nMotive: Job performance",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Frank E. Macher\nYear: 2003\nMotive: Voluntary turnover",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Charles G. McClure Jr.\nYear: 2004\nMotive: When to work in other company",
    "Firm: DUN & BRADSTREET \nCEO: Sara Mathew\nYear: 2013\nMotive: Voluntary turnover",
    "Firm: SEARS HOLDINGS \nCEO: Julian C. Day\nYear: 2003\nMotive: Departure following a marger adquisition",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: Richard Francis Syron\nYear: 2008\nMotive: Job performance",
    "Firm: ENESCO GROUP\nCEO: Thomas F. Bradley\nYear: 2004\nMotive: Departure following a marger adquisition",
    "Firm: ION GEOPHYSICAL \nCEO: Robert P. Peebler\nYear: 2011\nMotive: Voluntary turnover",
    "Firm: DANA\nCEO: Michael J. Burns\nYear: 2007\nMotive: Job performance",
    "Firm: ENESCO GROUP\nCEO: Cynthia Passmore\nYear: 2005\nMotive: Departure following a marger adquisition",
    "Firm: CALLAWAY GOLF CO\nCEO: William C. Baker\nYear: 2005\nMotive: Departure following a marger adquisition",
    "Firm: SEARS HOLDINGS \nCEO: Aylwin B. Lewis\nYear: 2007\nMotive: Job performance",
    "Firm: SEARS HOLDINGS \nCEO: William Bruce Johnson\nYear: 2010\nMotive: Job performance",
    "Firm: CALLAWAY GOLF CO\nCEO: George Fellows\nYear: 2010\nMotive: Job performance",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Jos Maria Alapont\nYear: 2011\nMotive: Voluntary turnover",
    "Firm: TOYS R US\nCEO: Antonio Urcelay\nYear: 2014\nMotive: Voluntary turnover",
    "Firm: NTN BUZZTIME\nCEO: Dario L. Santana\nYear: 2008\nMotive: Departure following a marger adquisition",
    "Firm: ION GEOPHYSICAL \nCEO: R. Brian Hanson\nYear: 2018\nMotive: Voluntary turnover",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Robert Vrij\nYear: 2008\nMotive: Job performance",
    "Firm: TOYS R US\nCEO: Gerald L. Storch\nYear: 2012\nMotive: Job performance",
    "Firm: CARPENTER TECHNOLOGY \nCEO: Anne L. Stevens\nYear: 2010\nMotive: Job performance",
    "Firm: CHRISTOPHER & BANKS \nCEO: Lorna E. Nagler\nYear: 2009\nMotive: Job performance",
    "Firm: BIOLASE\nCEO: Federico Pignatelli\nYear: 2014\nMotive: Departure following a marger adquisition",
    "Firm: BIOLASE\nCEO: Jeffrey W. Jones\nYear: 2007\nMotive: Job performance",
    "Firm: BIOLASE\nCEO: Robert E. Grant\nYear: 2005\nMotive: When to work in other company",
    "Firm: BIOLASE\nCEO: David M. Mulder\nYear: 2010\nMotive: Job performance",
    "Firm: BIOLASE\nCEO: Jake P. St. Philip\nYear: 2008\nMotive: Job performance",
    "Firm: DANA\nCEO: John M. Devine\nYear: 2010\nMotive: Departure following a marger adquisition",
    "Firm: DANA\nCEO: Gary L. Convis\nYear: 2008\nMotive: Policy related problems",
    "Firm: NTN BUZZTIME\nCEO: Michael K. Fleming\nYear: 2009\nMotive: Departure following a marger adquisition",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Kenneth D. Denman\nYear: 2011\nMotive: Voluntary turnover",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: David M. Moffett\nYear: 2009\nMotive: Voluntary turnover",
    "Firm: BARRICK GOLD \nCEO: Kelvin P. M. Dushnisky B.Sc. (Hon.) J.D. M.Sc.\nYear: 2017\nMotive: When to work in other company",
    "Firm: BARRICK GOLD \nCEO: Aaron William Regent F.C.A. FCPA B.A. C.A\nYear: 2011\nMotive: Job performance",
    "Firm: CLAIRES STORES\nCEO: Eugene S. Kahn\nYear: 2011\nMotive: Job performance",
    "Firm: CLAIRES STORES\nCEO: James G. Conroy\nYear: 2012\nMotive: Voluntary turnover",
    "Firm: DANA\nCEO: James E. Sweetnam\nYear: 2010\nMotive: Voluntary turnover",
    "Firm: WAUSAU PAPER \nCEO: Henry C. Newell\nYear: 2013\nMotive: Job performance",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: John A. Koskinen\nYear: 2009\nMotive: Departure following a marger adquisition",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: Charles Edgar Haldeman Jr.\nYear: 2011\nMotive: Voluntary turnover",
    "Firm: NTN BUZZTIME\nCEO: Terry A. Bateman\nYear: 2010\nMotive: Voluntary turnover",
    "Firm: BARNES & NOBLE\nCEO: William J. Lynch Jr.\nYear: 2012\nMotive: When to work in other company",
    "Firm: CARPENTER TECHNOLOGY \nCEO: Gregory A. Pratt\nYear: 2010\nMotive: Voluntary turnover",
    "Firm: CARPENTER TECHNOLOGY \nCEO: Gregory A. Pratt\nYear: 2015\nMotive: Voluntary turnover",
    "Firm: NTN BUZZTIME\nCEO: Michael J. Bush\nYear: 2012\nMotive: Voluntary turnover",
    "Firm: CARPENTER TECHNOLOGY \nCEO: William A. Wulfsohn\nYear: 2014\nMotive: When to work in other company",
    "Firm: CHRISTOPHER & BANKS \nCEO: Larry C. Barenbaum\nYear: 2011\nMotive: Job performance",
    "Firm: CDI \nCEO: Robert M. Larney\nYear: 2014\nMotive: Voluntary turnover",
    "Firm: CDI \nCEO: H. Paulett Eberhart\nYear: 2013\nMotive: Job performance",
    "Firm: DANA\nCEO: Roger J. Wood\nYear: 2015\nMotive: Voluntary turnover",
    "Firm: SEARS HOLDINGS \nCEO: Louis Joseph D'Ambrosio\nYear: 2012\nMotive: Departure following a marger adquisition",
    "Firm: CALLAWAY GOLF CO\nCEO: Anthony S. Thornley\nYear: 2011\nMotive: Departure following a marger adquisition",
    "Firm: CHRISTOPHER & BANKS \nCEO: Joel N. Waller\nYear: 2012\nMotive: Departure following a marger adquisition",
    "Firm: CHRISTOPHER & BANKS \nCEO: Joel N. Waller\nYear: 2017\nMotive: Departure following a marger adquisition",
    "Firm: BARNES & NOBLE\nCEO: Michael P. Huseby\nYear: 2014\nMotive: Job performance",
    "Firm: CLAIRES STORES\nCEO: Beatrice Lafon\nYear: 2015\nMotive: Job performance",
    "Firm: FEDERAL HOME LOAN MORTG \nCEO: Donald H. Layton\nYear: 2018\nMotive: Voluntary turnover",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Rainer Jueckstock\nYear: 2014\nMotive: Departure following a marger adquisition",
    "Firm: SEARS HOLDINGS \nCEO: Edward Scott Lampert\nYear: 2017\nMotive: Job performance",
    "Firm: CLAIRES STORES\nCEO: James D. Fielding\nYear: 2013\nMotive: Job performance",
    "Firm: NTN BUZZTIME\nCEO: Jeffrey A. Berg CFA\nYear: 2014\nMotive: Departure following a marger adquisition",
    "Firm: CHRISTOPHER & BANKS \nCEO: LuAnn Via\nYear: 2016\nMotive: Job performance",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Eric J. Vetter\nYear: 2015\nMotive: Job performance",
    "Firm: DUN & BRADSTREET \nCEO: Robert P. Carrigan\nYear: 2018\nMotive: Job performance",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Kevin P. Freeland\nYear: 2014\nMotive: Job performance",
    "Firm: CDI \nCEO: Scott Freidheim\nYear: 2016\nMotive: Job performance",
    "Firm: WAUSAU PAPER \nCEO: Michael C. Burandt\nYear: 2014\nMotive: Departure following a marger adquisition",
    "Firm: BIOLASE\nCEO: Jeffrey M. Nugent\nYear: 2015\nMotive: Job performance",
    "Firm: FEDERAL-MOGUL HOLDINGS \nCEO: Daniel A. Ninivaggi\nYear: 2015\nMotive: When to work in other company",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Boris Teksler\nYear: 2016\nMotive: Departure following a marger adquisition",
    "Firm: TOYS R US\nCEO: David Allen Brandon\nYear: 2016\nMotive: Departure following a marger adquisition",
    "Firm: BIOLASE\nCEO: Harold C. Flynn Jr.\nYear: 2017\nMotive: Job performance",
    "Firm: BARNES & NOBLE\nCEO: Ronald D. Boire\nYear: 2015\nMotive: Job performance",
    "Firm: GREAT ELM CAPITAL GROUP\nCEO: Richard S. Chernicoff J.D.\nYear: 2017\nMotive: Departure following a marger adquisition",
    "Firm: CLAIRES STORES\nCEO: Ronald Marshall\nYear: 2017\nMotive: Job performance",
    "Firm: BARNES & NOBLE\nCEO: Demos Parneros\nYear: 2017\nMotive: Policy related problems"
  ) |>
    structure(class = c("glue", "character")),
  fyear = c(
    1997, 2008, 2007, 1998, 2003, 1993, 1996, 1999, 1994, 1993, 1999, 1997, 2005,
    2002, 2001, 2002, 1996, 1997, 1993, 1994, 1997, 2011, 1995, 2000, 1995, 2000,
    1998, 1996, 1996, 1993, 1995, 1999, 1996, 1996, 2001, 2016, 1997, 2006, 2002,
    2000, 1997, 2003, 2009, 1998, 2003, 1999, 2000, 1998, 1999, 1999, 2003, 2006,
    1998, 1999, 2006, 2000, 2004, 2002, 2002, 2013, 2004, 2001, 2004, 2001, 2000,
    2005, 2006, 2005, 2004, 2009, 2003, 2010, 2014, 2003, 2004, 2013, 2003, 2008,
    2004, 2011, 2007, 2005, 2005, 2007, 2010, 2010, 2011, 2014, 2008, 2018, 2008,
    2012, 2010, 2009, 2014, 2007, 2005, 2010, 2008, 2010, 2008, 2009, 2011, 2009,
    2017, 2011, 2011, 2012, 2010, 2013, 2009, 2011, 2010, 2012, 2010, 2015, 2012,
    2014, 2011, 2014, 2013, 2015, 2012, 2011, 2012, 2017, 2014, 2015, 2018, 2014,
    2017, 2013, 2014, 2016, 2015, 2018, 2014, 2016, 2014, 2015, 2015, 2016, 2016,
    2017, 2015, 2017, 2017, 2017
  ),
)
````


```
library(ggtext)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggiraph)
library(glue)

voluntary_col <- "#894843"
involuntary_col <- "#887d74"
bg_color <- "#D7E0DA"
font_color <- "#1f3225"
hover_color <- "#4c6061"

title <- "CEO DEPARTURES"

subtitle <- glue("CEO **<span style = 'color:{voluntary_col}'>voluntary</span>** and 
**<span style= 'color:{involuntary_col}'>involuntary</span>** departures 
in the 20 *S&P 1500* firms<br>with most CEO rotation between 1993 and 2018")

caption <- "Data comes from Gentry et al. Facilitated by DatalsPlural. Visualization by Martín Pons | @MartinPonsM"

departures_theme <- theme(
  text = element_text(color = font_color, family = "Open Sans"),
  plot.title = element_text(hjust = 0.5),
  plot.subtitle = element_textbox(halign = .5, hjust = .5, family = "Open Sans", size = 8),
  plot.caption = element_text(size = 6, hjust = .9),
  plot.background = element_rect(fill = bg_color, color = bg_color),
  panel.background = element_rect(fill = bg_color, color = bg_color),
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# get number of voluntary and involuntary departures
departure_firms_main_cause <- departures %>%
  count(coname, main_cause) %>%
  pivot_wider(
    names_from = main_cause, values_from = n,
    values_fill = 0) %>% 
  mutate(
    firm_label = glue("{coname}:\nVoluntary departures: {voluntary}\nInvoluntary departures: {involuntary}")
  )
departure_firms_main_cause
gg_departures <- ggplot(data = departures, mapping = aes(fyear)) +
  geom_col_interactive(
    mapping = aes(y = 1, fill = main_cause, 
                  tooltip = tooltip, data_id = coname),
    color = bg_color, linewidth = 1, show.legend = FALSE) +
  geom_text_interactive(
    data = departure_firms_main_cause, 
    aes(x = 1994, y = 9.2, label = firm_label, data_id = coname),
    color = hover_color, size = 2.5, hjust = "left", alpha = 0) +
  labs(title = title, subtitle = subtitle, caption = caption) +
  scale_fill_manual(values = c(voluntary_col, involuntary_col)) +
  scale_x_continuous(labels = formatC, breaks = seq(1995, 2015, by=5)) +
  departures_theme +
  coord_equal()

girafe(
  ggobj = gg_departures, 
  bg = bg_color,
  options = list(
    opts_tooltip(
      opacity = 0.8, use_fill = TRUE,
      use_stroke = FALSE, 
      css = "padding:5pt;font-family: Open Sans;font-size:1rem;color:white"),
    opts_hover_inv(css = "opacity:0.4"), 
    opts_toolbar(saveaspng = FALSE),
    opts_zoom(max = 1),
    opts_hover(
      css = girafe_css(
        css = glue("fill:{font_color};"),
        text = glue("stroke:none;fill:{font_color};fill-opacity:1;")
      ))
  )
)
```

<img width="607" alt="Capture d’écran 2024-11-19 à 10 14 01" src="https://github.com/user-attachments/assets/b756dc69-9565-4538-895b-7635b1bae1e3">

**Closed** 2024-11-19 09:16 UTC
