### ISSUE TITLE
download png - missing font 

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/ggiraph#231] opened 2022-09-17 07:58 UTC
When using a specific font, embed in the web page, the save-as-png util does not seem to find the font. 

@pepijn-devries

```
library(systemfonts)
library(ggiraph)
library(ggplot2)
library(shiny)


if (!dir.exists("www")) {
  dir.create("www")
  library(gfonts)
  setup_font(
    id = "ms-madi",
    output_dir = "www",
    variants = "regular",
    prefer_local_source = FALSE)
}

if(!font_family_exists("Ms Madi")){
  register_font(name = "Ms Madi",
                plain = list("www/fonts/ms-madi-v2-latin-regular.woff", 0)
  )
}

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            sliderInput("num_rows",
                        "Number of rows:",
                        min = 15,
                        max = 32,
                        value = 20),
            verbatimTextOutput("verbat")
        ),

        # Show a plot of the generated distribution
        mainPanel(
          tags$link(
            rel = "stylesheet",
            href="css/ms-madi.css"
          ),
          girafeOutput("custofontplot")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$custofontplot <- renderGirafe({
        # generate bins based on input$bins from ui.R
      dat <- mtcars[seq_len(input$num_rows),]
      dat$carname <- row.names(dat)

      gg <- ggplot(dat, aes(drat, carname)) +
        geom_point() +
        theme_minimal(base_family = "Ms Madi")

      girafe(ggobj = gg)
    })

    output$verbat <- renderPrint({
      fs::dir_tree(".")
    })
}

# Run the application
shinyApp(ui = ui, server = server)
```

**Comment by sigmapi** [comment] 2022-09-17 13:39
I'm not sure why, but I  can't reproduce it

**Comment by pepijn-devries** [comment] 2022-09-18 07:10
Hi,

After some googling, I've come across the following issues that may be related:

https://github.com/exupero/saveSvgAsPng/issues/172
https://stackoverflow.com/questions/69158165/download-svg-element-with-custom-font-to-png

Perhaps they can help in the process of tracing the problem?

**Comment by sigmapi** [comment] 2022-09-19 07:54
I took a look at this:
`save-as-png` takes the first font url from each font-face declaration.
In this case, as `gfonts` gives it, it's 
```
url('../fonts/ms-madi-v2-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
```
This is an eot format which is supported only in IE, specifically for IE6-IE8... No modern browser supports it. 
(Once again, I cannot digest that we still must give support to a dead browser)

Delete this url from ms-madi.css  (line 7) and `save-as-png` will take the next url which is woff2 format and the font will be rendered ok. (Except in IE which does not support woff2 format). 

I think that we can work this out, by scanning in `ggiraph` the css rules, choose a widely supported format (woff or ttf will work everywhere) and pass the font list to `save-as-png`.

**Comment by pepijn-devries** [comment] 2022-09-19 08:32
@sigmapi Thanks for looking into this. I can confrim that removing these lines from the css file fixes the problem. I can live in a world where IE is not supported ;).

This sollution seems more like a work-around than an actual fix. But I'm not sure whether this should be addressed in the ggiraph package or the gfonts package...

**Closed** 2022-09-24 13:54 UTC

**Comment by sigmapi** [comment] 2022-09-24 13:57
Hey @pepijn-devries , the issue is now fixed, please try it in the latest github version

**Comment by pepijn-devries** [comment] 2022-09-24 20:11
Hi @sigmapi, thanks for the update. I've just tested the github version in my project. The png download now works nicely!
