### ISSUE TITLE
when using (horizontal) grid, labels of facets disappear

### ISSUE THREAD

**Issue by masalmon** [davidgohel/ggiraph#12] opened 2016-02-22 12:23 UTC
1. Cool package, thanks!

2. I have tried using geom_point_interactive for a graph with a grid. When using the interactive version of the graph, the labels of the facets disappear. Here is a reproducible example.

```r
library("ggplot2")
library("ggiraph")
p <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
# With one variable
p + facet_grid(cyl ~ .)

p2 <-  ggplot(mtcars, aes(mpg, wt, tooltip = wt)) +
  geom_point_interactive()+
  facet_grid(cyl ~ .)
p2
ggiraph(code = {print(p2)}, width = 10, height = 10)

```

It doesn't happen for facet_grid(. ~cyl).

```r

p2 <-  ggplot(mtcars, aes(mpg, wt, tooltip = wt)) +
  geom_point_interactive()+
  facet_grid(. ~ cyl)
p2
ggiraph(code = {print(p2)}, width = 10, height = 10)

```

**Comment by davidgohel** [comment] 2016-02-25 09:42
Hi,

This is a duplicate of #9 that has just been fix

David

**Closed by davidgohel** 2016-02-25 09:42 UTC

**Comment by masalmon** [comment] 2016-02-25 10:08
cool, thanks!

**Comment by davidgohel** [comment] 2016-02-25 10:16
the fix was to be done in rvg, I will submit the new ggiraph version soon.

For now, best is 

    install.packages("rvg")
    devtools::install_github("davidgohel/ggiraph") # new version with d3.js instead of bootstrap

David

**Comment by masalmon** [comment] 2016-02-25 10:17
Ok, many thanks again! Ou bien merci ! :-)

**Comment by davidgohel** [comment] 2016-02-25 10:19
de rien!
