### ISSUE TITLE
Hover Effect on Blogdown Posts

### ISSUE THREAD

**Issue by ehbick01** [davidgohel/ggiraph#86] opened 2018-02-05 20:22 UTC
Hey!

When building a `geom_rect_interactive` object across separate rmd files that are then rendered as separate blog posts, the data-id for the last rmd rendered is used across all of the geom_rect_interactive objects. Below is my session info:

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
LC_TIME=English_United States.1252    

attached base packages:
stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
bindrcpp_0.2        scales_0.5.0        tm_0.7-3            NLP_0.1-11         
ggiraph_0.4.2       plotly_4.7.1        knitr_1.19          kableExtra_0.7.0   
xtable_1.8-2        formattable_0.2.0.1 forcats_0.2.0       stringr_1.2.0      
dplyr_0.7.4         purrr_0.2.4         readr_1.1.1         tidyr_0.8.0        
tibble_1.4.2        ggplot2_2.2.1       tidyverse_1.2.1     mapproj_1.2-5      
maps_3.2.0          blogdown_0.5       

loaded via a namespace (and not attached):
httr_1.3.1          jsonlite_1.5        viridisLite_0.3.0   R.utils_2.6.0      
modelr_0.1.1        assertthat_0.2.0    cellranger_1.1.0    slam_0.1-42        
yaml_2.1.16         gdtools_0.1.6       pillar_1.1.0        backports_1.1.2    
lattice_0.20-35     glue_1.2.0          uuid_0.1-2          digest_0.6.15      
rvest_0.3.2         colorspace_1.3-2    htmltools_0.3.6     httpuv_1.3.5       
R.oo_1.21.0         plyr_1.8.4          psych_1.7.8         pkgconfig_2.0.1    
broom_0.4.3         servr_0.8           haven_1.1.1         bookdown_0.6       
later_0.6           officer_0.2.1       lazyeval_0.2.1      cli_1.0.0          
mnormt_1.5-5        magrittr_1.5        crayon_1.3.4        readxl_1.0.0       
mime_0.5            evaluate_0.10.1     R.methodsS3_1.7.1   nlme_3.1-131       
xml2_1.2.0          foreign_0.8-69      tools_3.4.3         data.table_1.10.4-3
hms_0.4.1           munsell_0.4.3       zip_1.0.0           compiler_3.4.3     
rlang_0.1.6         grid_3.4.3          rstudioapi_0.7      htmlwidgets_1.0    
base64enc_0.1-3     rmarkdown_1.8       gtable_0.2.0        reshape2_1.4.3     
R6_2.2.2            rvg_0.1.7           lubridate_1.7.1     bindr_0.1          
rprojroot_1.3-2     stringi_1.1.6       parallel_3.4.3      Rcpp_0.12.15       
xfun_0.1 
```

**Comment by davidgohel** [comment] 2018-02-05 20:28
Thanks,

What is the effect of that for you? 

ggiraph ID are managed by their data-id and the svg id. There should not be conflicts inside a html document generated from rmarkdown. But I am not an expert with bookdown so may be I miss something?

**Comment by ehbick01** [comment] 2018-02-05 21:27
When I hover over the bars for an image on any post, it displays in the tooltip the corresponding data for the chart that is rendered in the most recent post. The bars themselves build fine - it is only happening in the tooltip itself.

**Comment by davidgohel** [comment] 2018-02-05 21:41
OK, I will have a look.

(It would help if you could provide an example.)

**Comment by ehbick01** [comment] 2018-02-05 23:59
I'll see if I can work up a shareable reprex tomorrow! Unfortunately, the example I do have has sensitive info in it :/

**Comment by davidgohel** [comment] 2018-02-06 00:25
thanks

**Comment by davidgohel** [comment] 2018-06-10 14:58
I am closing that issue, I will reopen it if necessary, for now I could not reproduce any issue with blogdown.

**Closed by davidgohel** 2018-06-10 14:58 UTC
